temperature:
  i3_cpu:
    prefix: ğŸ§ 
    json_path: $.k10temp-pci-00c3.Tctl.temp1_input
    suffix: Â°C

  i3_gpu:
    prefix: ğŸ–¥ï¸
    json_path: $.amdgpu-pci-0900.edge.temp1_input
    suffix: Â°C

ip:
  tmux:
    interface: ['enp6s0']
    no_ip: No address
